"""
Created: 2024-12-10
Last Updated: 2025-01-13
Last Updated by: Desmond

Description:
- Holds the common constants used for all the scripts within the PoC App
- To import from any scripts within the PoC App directory: "from constants import *"
- Constants holding column/header names:
    - The prefix [N] in column names refers to data extracted from NLB API
    - The prefix [G] in column names refers to data extracted from Google API
    - For those without prefixes, they are from QS
    - The prefix [LLM] in column names refers to data derived thru LLM

"""

DELIM = "```"
UNK = 'unknown'


LLM_COMP_FILE = './data/LLM_completions_record.csv'
HASH_STR = 'Hash String'
LLM_RAW = 'LLM Raw Response'

CONTENT_FILE = './data/content.csv'
# CONTENT_FILE = './data/Sample_20241211.csv'
STATS_FILE = './data/content_statistics.csv'

TEST_FILE1 = './data/test_data_01.csv'
TEST_FILE2 = './data/test_data_02.csv'
TEST_FILE3 = './data/test_data_03.csv'

TEST_FILE4 = './data/test_data_04.csv'
TEST_FILE5 = './data/test_data_05.csv'
TEST_FILE6 = './data/test_data_06.csv'

TEST_FILE7 = './data/test_data_07.csv'
TEST_FILE8 = './data/test_data_08.csv'
TEST_FILE9 = './data/test_data_09.csv'

TEST_FILE10 = './data/test_data_10.csv'
TEST_FILE11 = './data/test_data_11.csv'
TEST_FILE12 = './data/test_data_12.csv'


# Raw file consolidating the content's metatdata 
ISBN = 'ISBN'
TITLE = 'Title'
N_TITLE = '[N] Title'
G_TITLE = '[G] Title'
AUTH = 'Author'
N_AUTH = '[N] Author'
G_AUTH = '[G] Author'
N_SUBJ = '[N] Subjects'
G_SUBJ = '[G] Subjects'
N_ABST = '[N] Abstract'
N_NOTES = '[N] Notes'
N_PHY_DESC = '[N] Physical Description'
G_PG_CNT = '[G] Page Count'
DDC = 'Item DDC Code'
MEDIA = 'Item Media'
TITLE_PUB_DTE = 'Title Publication Date'
G_PUB_DTE = '[G] Published Date'
N_COVER_URL = '[N] Cover URL'
G_COVER_URL = '[G] Cover URL'

PUB_DTE = 'Cleaned Publication Date'  # Cleaned and derived from TITLE_PUB_DTE & G_PUB_DTE

LLM_DDC = '[LLM] DDC Description'
LLM_PG_CNT = '[LLM] Page Count'

LLM_TOPIC = '[LLM] Topic'
LLM_SUBTOPIC = '[LLM] Sub-Topic'
LLM_LVL = '[LLM] Level'

N_TOKENS = 'Num Tokens'
REASON = 'Reasoning'

FORMAT = 'Cleaned Media Format'  # Refer to MEDIA_FORMATS for its derived values

MODEL_DEFAULT = "gpt-4o"   # Alt: "gpt-3.5-turbo", "gpt-4o-mini"


# The following were discussed & agreed by the team on 2024-12-20
# An original list of sub-topics were generated by LLM premised on popularity, which facilitated the discussion
TOPICS = [
    "Digital",
    "Sustainability",
    "Science & Engineering",
    "Singapore",
    "Wellness",
    "Arts",
    "Personal Development"
]

TOPICS_SUBTOPICS = {
    "Digital": [
        "Artificial Intelligence & Machine Learning",
        "Cyber Security",
        "Data Science & Analytics",
        "Internet of Things",
        "Cloud Computing",
        "Blockchain Technology",
        "Software Engineering"
    ],
    "Sustainability": [
        "Climate Change",
        "Environmental Conservation",
        "Renewable Energy",
        "Sustainable Living",
        "Green Economy"
    ],
    "Science & Engineering": [
        "Astronomy & Space Exploration",
        "Biology & Medical Science",
        "Chemistry",
        "Physics",
        "Quantum Computing",
        "Engineering",
        "Mathematics"
    ],
    "Singapore": [
        "Economic Development",
        "SG Culture & Heritage", 
        "Urban Planning",
        "Education",
        "Food & Beverage"
    ],
    "Wellness": [
        "Mental Health",
        "Physical Health",
        "Nutrition",
        "Mindfulness",
        "Fitness"
    ],
    "Arts": [
        "Visual Arts",
        "Performing Arts",
        "Culture & Heritage",
        "Literary Arts",
        "Film & Television",
        "Digital Arts",
        "Culinary Arts",
        "Handicraft"
    ],
    "Personal Development": [
        "Self-Help",
        "Finance & Investment",
        "Career Development",
        "Time Management",
        "Emotional Intelligence"
    ]
}

LEVELS = [
    "Beginner",
    "Intermediate",
    "Advanced"
]

MEDIA_FORMATS = [
    "book",
    "ebook",
    "program"
]

OMAKASES = {
    "Beginner": [
        {"Level": "Beginner", "Format": "program"}, 
        {"Level": "Beginner", "Format": "book"}, 
        {"Level": "Intermediate", "Format": "program"}
    ],
    "Intermediate": [
        {"Level": "Intermediate", "Format": "program"}, 
        {"Level": "Intermediate", "Format": "book"}, 
        {"Level": "Advanced", "Format": "book"}
    ],
    "Advanced": [
        {"Level": "Advanced", "Format": "book"}, 
        {"Level": "Advanced", "Format": "book"}, 
        {"Level": "Advanced", "Format": "book"}
    ]
}

PHASES = [
    "Appetiser",
    "Main",
    "Dessert"
]